### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by jonchui** [MrFlynn/2fa-copier#1]
Love this idea (since apple only does it for safari, haha and i use chrome)_

Can't seem to figure out how to install it? it seems i'm supposed to run the ruby `install` function?

When i try to run the applescript, i get this error:

`error "bash: message.sh: No such file or directory" number 127`

even after `chmod +x message.sh`

i can run message.sh from command line (it returns -1)

**Comment by MrFlynn** [comment]
Hi Jon,

In theory, you should be able to install it using `brew tap MrFlynn/2fa-copier && brew install 2fa-copier` (or something similar to that--I don't recall the exact command from the top of my head). I set this up on my old laptop running Sierra and it appears that I never updated the install instructions in this repo. I haven't set this up on my current machine on Mojave so I have no idea if the homebrew installation method or the script work anymore.

I can try to finalize the installation instructions and verify that it still works this weekend. I'd like to get this working on my new laptop, but it's been at the bottom of my todo list for a while.

**Comment by MrFlynn** [comment]
I looked into getting this working last night, and I discovered that Apple basically broke the functionality of this script in one of last two updates. I explored a couple of other options to get this working, but I've found nothing promising thus far.

I'll give it another try this weekend to see if I can find an alternative method, but I can't guarantee anything at this point.

**Comment by MrFlynn** [comment]
It looks like Apple has removed the ability to read text messages directly from the messages app database and I haven't had luck with reading directly from Notification Center's database either (relevant contents seem to be garbled or encoded in some manner that isn't obvious to me). So it's safe to say this script is permanently broken. Sorry about that.
